CREATE TABLE VOYQUERY(
SEQ int,
QUERY varchar(1000),
PREFIXES varchar(100),
IS_LEAVE_QUERY int,
INPUT_VAR varchar(200),
OUTPUT_VAR varchar(200),
OUTPUT_REL varchar(100),
DESCRIPTION varchar(1000)
);

CREATE TABLE VOYQUERY_DATA(
URI varchar(100),
MAP_BINDING varchar(50)
);

CREATE TABLE VOYPREFIX(
PREFIX varchar(50),
URI varchar(100)
);
