CREATE TABLE VOYQUERY(
ID int,
SEQ int,
QUERY varchar(1000),
PREFIX varchar(100),
IS_LEAVE_QUERY int,
INPUT_VAR varchar(200),
OUTPUT_VAR varchar(200),
OUTPUT_REL varchar(100),
DESCRIPTION varchar(1000)
);

CREATE TABLE VOYQUERY_DATA(
URI varchar(300) NOT NULL,
INPUT_VAR varchar(100) NOT NULL,
PRIMARY KEY(URI, INPUT_VAR)
);

CREATE TABLE VOYPREFIX(
PREFIX varchar(50),
URI varchar(100)
);
