CREATE TABLE VOYQUERY(
ID int,
SEQ int,
QUERY varchar(1000),
PREFIX varchar(100),
IS_LEAVE_QUERY int,
INPUT_VAR varchar(200),
OUTPUT_VAR varchar(200),
OUTPUT_REL varchar(100),
DESCRIPTION varchar(1000)
);

CREATE TABLE VOYQUERY_DATA(
URI varchar(300) NOT NULL,
INPUT_VAR varchar(100) NOT NULL,
PRIMARY KEY(URI, INPUT_VAR)
);

CREATE TABLE VOYLABEL(
ID int NOT NULL,
URI varchar(300) NOT NULL,
LABEL varchar(200),
PRIMARY KEY(ID)
);

CREATE TABLE VOYLABEL_NGRAM(
NGRAM varchar(10) NOT NULL,
LABEL_ID int NOT NULL,
PRIMARY KEY(NGRAM, LABEL_ID)
);

CREATE TABLE VOYPREFIX(
PREFIX varchar(50),
URI varchar(100)
);

CREATE TABLE VOYLINKAGE(
ENTITY_1 varchar(200) NOT NULL,
ENTITY_2 varchar(200) NOT NULL, 
PAGE_URI varchar(300),
DISTANCE int
);

CREATE TABLE VOYCITIES(
CITY_NAME varchar(100),
LATITUDE double precision,
LONGTITUDE double precision,
COUNTRY_CD varchar(2),
POPULATION int,
);

CREATE TABLE VOYCOUNTRIES(
COUNTRY_CD varchar(2),
COUNTRY_NAME varchar(100),
CAPITAL varchar(100),
AREA int,
POPULATION int,
CONTINENT varchar(2),
CURRENCY varchar(3)
);

CREATE TABLE VOYPAGECONTEXT(
PAGE_URI varchar(300),
CONTEXT varchar(10000)
);
